import './styles/RNG.css'

export default function RandomNameGenerator(){
    const maleHumanName = [
        "Leonard ",
        "Joseph ",
        "Andrew ",
        "Timothy ",
        "Reynald ",
        "Thomas ",
        "Matthew ",
        "Arnold ",
        "Henry ",
        "Eric ",
        "Logan ",
        "Samuel ",
        "Drake ",
        "Harold ",
        "William ",
        "Richard ",
        "Roy ",
        "Quinten ",
        "Liam ",
        "Oliver ",
        "Elijah ",
        "James ",
        "Benjamin ",
        "Lucas ",
        "Ethan ",
        "Daniel ",
        "Jacob ",
        "Jackson ",
        "Levi ",
        "Sebastian ",
        "Owen ",
        "Aiden ",
        "Wyatt ",
        "David ",
        "Asher ",
        "Jayden ",
        "Anthony ",
        "Dylan ",
        "Ezra ",
        "Charles ",
        "Josiah ",
        "Isaiah ",
        "Caleb ",
        "Nathaniel ",
        "Miles ",
        "Nolan ",
        "Cody ",
        "Colton ",
        "Hunter ",
        "Axel ",
        "Landon ",
        "Cooper ",
        "Jeremiah ",
        "Connor ",
        "Angel ",
        "Jordan ",
        "Ian ",
        "Carson ",
        "Nicholas ",
        "Dominic ",
        "Everett ",
        "Xavier ",
        "Jose ",
        "Jace ",
        "Wesley ",
        "Silas ",
        "Adam ",
        "Michael ",
        "Mason ",
        "Johnathan ",
        "Theodore ",
        "Lincoln ",
        "Gabriel ",
        "Winston ",
        "Ryan ",
        "Adrian ",
        "Ezekiel ",
        "Easton ",
        "Roman ",
        "Weston ",
        "Robert ",
        "Edmund ",
        "Greyson ",
        "Austin ",
        "Kai ",
        "Kyle ",
        "Bennett ",
        "Waylon ",
        "Evan ",
        "Gael ",
        "Harrison ",
        "Bryson ",
        "Micha ",
        "Joel ",
        "Arthur ",
        "Damian ",
        "Beauregard ",
        "Emmett ",
        "Declan ",
        "Dalton ",
        "Donovan ",
    ];
    const femaleHumanName = [
        "Olivia ",
        "Emma ",
        "Ava ",
        "Charlotte ",
        "Sophia ",
        "Amelia ",
        "Isabella ",
        "Mia ",
        "Evelyn ",
        "Camila ",
        "Gianna ",
        "Abigail ",
        "Luna ",
        "Ella ",
        "Elizabeth ",
        "Sofia ",
        "Emily ",
        "Avery ",
        "Mila ",
        "Scarlett ",
        "Eleanor ",
        "Madison ",
        "Layla ",
        "Penelope ",
        "Aria ",
        "Chloe ",
        "Grace ",
        "Ellie ",
        "Nora ",
        "Hazel ",
        "Zoey ",
        "Riley ",
        "Victoria ",
        "Lily ",
        "Aurora ",
        "Violet ",
        "Nova ",
        "Hannah ",
        "Emilia ",
        "Zoe ",
        "Stella ",
        "Everly ",
        "Isla ",
        "Leah ",
        "Lillian ",
        "Addison ",
        "Willow ",
        "Lucy ",
        "Paisley ",
        "Natalie ",
        "Naomi ",
        "Eliana ",
        "Brooklyn ",
        "Elena ",
        "Aubery ",
        "Claire ",
        "Ivanka ",
        "Kinsley ",
        "Audrey ",
        "Maya ",
        "Skylar ",
        "Belladonna ",
        "Savannah ",
        "Anna ",
        "Delilah ",
        "Serenity ",
        "Caroline ",
        "Ruby ",
        "Alice ",
        "Gabriella ",
        "Sadie ",
        "Ariana ",
        "Allison ",
        "Natalia ",
        "Hailey ",
        "Josephine ",
        "Sarah ",
        "Cora ",
        "Piper ",
        "Samantha ",
        "Eva ",
        "Lydia ",
        "Madeline ",
        "Jade ",
        "Peyton ",
        "Brielle ",
        "Adeline ",
        "Vivian ",
        "Rylee ",
        "Clara ",
        "Julia ",
        "Athena ",
        "Eliza ",
        "Kaylee ",
        "Layla ",
        "Remi ",
        "Mackenzie ",
        "Isabelle ",
        "Margaret ",
        "Elliana ",
        "Faith ",
    ];
    const humanLastName = [
        "Smith",
        "Jones",
        "Taylor",
        "Brown",
        "Williams",
        "Wilson",
        "Johnson",
        "Davies",
        "Robinson",
        "Wright",
        "Thompson",
        "Evans",
        "Walker",
        "White",
        "Roberts",
        "Green",
        "Hall",
        "Wood",
        "Jackson",
        "Clark",
        "Ford",
        "Phillips",
        "Wilson",
        "Clarke",
        "Mitchell",
        "Cox",
        "Alexander",
        "Mason",
        "Lewis",
        "Kelly",
        "Campbell",
        "Moore",
        "Johnston",
        "Doherty",
        "Stewart",
        "Quinn",
        "Murphy",
        "Graham",
        "Martin",
        "Hamilton",
        "Hughes",
        "Murray",
        "Anderson",
        "Scott",
        "Reid",
        "Rossland",
        "Young",
        "Watson",
        "Paterson",
        "Morrison",
        "Morgan",
        "Jenkins",
        "Griffiths",
        "Edwards",
        "Price",
        "Moss",
        "Driscoll",
        "Rees",
        "Bernard",
        "Petit",
        "Durand",
        "Leroy",
        "Moreau",
        "Simon",
        "Laurent",
        "Michel",
        "Garcia",
        "Bertrand",
        "Vincent",
        "Baker",
        "Miller",
        "Morel",
        "Bonnet",
        "Despire",
        "Roux",
        "Muller",
        "Schmidt",
        "Schneider",
        "Fisher",
        "Colt",
        "Becket",
        "Becker",
        "Wagner",
        "Weber",
        "Schulz",
        "Killingsworth",
        "Rider",
        "Hoffmann",
        "Sooner",
        "Farkas",
        "Wulfred",
        "Olsen",
        "Jensen",
        "Hansen",
        "Lynch",
        "Rossi",
        "Conti",
        "Villa",
        "Core",
    ];
    function nameGen() {
        if(document.getElementById('male').checked){
            let result = Math.floor(Math.random() * 100);
            let result2 = Math.floor(Math.random() * 100);
            document.getElementById("random-name-output").innerHTML += maleHumanName[result] + " " + humanLastName[result2] +"\n";
            document.getElementById("random-name-output").scrollTo(0,50000);
        }
        if (document.getElementById('female').checked){
            let result = Math.floor(Math.random() * 100);
            let result2 = Math.floor(Math.random() * 100);
            document.getElementById("random-name-output").innerHTML += femaleHumanName[result] + " " + humanLastName[result2] +"\n";
            document.getElementById("random-name-output").scrollTo(0,50000);
        }
        if (document.getElementById('both').checked) {
            let coinToss = Math.floor(Math.random() * 2) + 1;
            if (coinToss === 1){
                let result = Math.floor(Math.random() * 100);
                let result2 = Math.floor(Math.random() * 100);
                document.getElementById("random-name-output").innerHTML += maleHumanName[result] + " " + humanLastName[result2] +"\n";
                document.getElementById("random-name-output").scrollTo(0,50000);
            }
            else {
                let result = Math.floor(Math.random() * 100);
                let result2 = Math.floor(Math.random() * 100);
                document.getElementById("random-name-output").innerHTML += femaleHumanName[result] + " " + humanLastName[result2] +"\n";
                document.getElementById("random-name-output").scrollTo(0,50000);
            }
        }
        sessionStorage.setItem("random-names", document.getElementById("random-name-output").value);
        let genSound = new Audio("src/assets/sounds/EnergyAmmoConversion.wav");
        genSound.volume=0.10;
        genSound.play();
    };
    function resetText() {
        document.getElementById("random-name-output").innerHTML = " ";
        sessionStorage.setItem("random-names", document.getElementById("random-name-output").value);
    };
    //following code returns null, need to investigate further
    //document.getElementById("random-name-output").innerHTML = sessionStorage.getItem("random-names");

    return(
        <div id="main">
            <h3 id="main_title">Random Name Generator</h3>
            <div id="content">
                <form>
                    <label for="male">Male<input type="radio" id="male" name="gender"/></label><br/>
                    <label for="female">Female<input type="radio" id="female" name="gender"/></label><br/>
                    <label for="both">Both<input type="radio" id="both" name="gender"/></label><br/>
                    <p id="rno-ui">
                        <button type="button" id="human" onClick={nameGen}>Generate Human Name</button>
                        <button type="button" id="clear-name-output" onClick={resetText}>Clear</button>
                    </p>
                    <textarea id="random-name-output" readOnly={true}></textarea>
                </form>
            </div>
        </div>)
};